### ISSUE TITLE
Binding KeyEquivalent disables -validateMenuItem: Call

### ISSUE THREAD

**Issue by bdkjones** [Kentzo/ShortcutRecorder#38] opened 2015-04-23 00:57 UTC
I have an NSMenuItem. If I bind `keyEquivalent` and `keyEquivalentModifierMask` as shown in README, then `-validateMenuItem:` is no longer called for this menuItem. As soon as I remove the bindings, `-validateMenuItem:` is called correctly for the menuItem.

This is a problem for me because the logic in `-validateMenuItem:` changes the item's title appropriately and enables/disables as appropriate. 

Can this be fixed?

**Comment by Kentzo** [comment] 2015-05-06 06:52
@bdkjones Sorry for delay.

Could you upload a demo of that issue?

**Comment by DanielGibbsNZ** [comment] 2015-06-23 04:11
I'm also having this problem, although it doesn't look like it's a bug in ShortcutRecorder, but rather in AppKit. See a similar issue [here](http://stackoverflow.com/questions/3337233/binding-an-nsmenuitems-title-breaks-enabled-disabled-validation).

**Comment by Kentzo** [comment] 2015-06-23 14:24
I suppose you cannot combine both validation and bindings.

**Comment by JanX2** [comment] 2017-02-23 12:27
I have the same issue @bdkjones. Did you find a workaround? I am thinking that it should be possible somehow to find out what AppKit now believes the target is for calling `-validateMenuItem:`. Or if something short-circuits so that it’s not called anywhere at all. 

[Add a symbolic breakpoint on a selector in Xcode](http://stackoverflow.com/questions/8264193/add-a-symbolic-breakpoint-on-a-selector-in-xcode) describes how to set a breakpoint on `-[NSObject validateMenuItem:]`, but this doesn’t work for me regardless of whether there actually is an implementation on a target or not. Breakpoints within its implementation work fine. That’s where I am stuck for now.

**Comment by JanX2** [comment] 2017-02-23 20:53
It appears that I have found a workaround for this issue. It is working in my tests at least. 

```
- (void)awakeFromNib
{
	[super awakeFromNib];
	
	[self initKeyBindingsController];

	_menuItemSet = [NSMutableSet set];

	// …
}
```

Then call the following method for every menu item:
```
- (void)setupMenuDelegateForMenuItem:(NSMenuItem *)menuItem
{
	[_menuItemSet addObject:menuItem];
	
	NSMenu *menu = menuItem.menu;
	
	id <NSMenuDelegate> selfAsDelegate = (id <NSMenuDelegate>)self;
	
	if (menu.delegate != selfAsDelegate) {
		// TODO: Keep old menu delegate around as a week ref and forward all messages there.
		menu.delegate = selfAsDelegate;
	}
}
```

Finally, we implement part of the the `NSMenuDelegate` protocol.

```
- (NSInteger)numberOfItemsInMenu:(NSMenu *)menu;
{
	return menu.numberOfItems;
}

- (BOOL)menu:(NSMenu *)menu
  updateItem:(NSMenuItem *)menuItem
	 atIndex:(NSInteger)index
shouldCancel:(BOOL)shouldCancel;
{
	BOOL canContinue = YES;
	
	if (shouldCancel)  return canContinue;
	
	if ([_menuItemSet containsObject:menuItem]) {
		id target = menuItem.target;
		[target validateMenuItem:menuItem];
	}
	
	// TODO: Forward to old menu delegate.
	
	return canContinue;
}
```

**Comment by Kentzo** [comment] 2017-02-24 05:45
@JanX2 I elsewhere found disassembled AppKit framework made by someone else and analyzed it.

The method of our interest is `-[NSMenuItem _enableItem]`. Its implementation seems to check boolean option in NSUserDefaults named "NSTrackMenuValidation". When set, it prints additional debugging information to the console. Try it, maybe it will get us something useful.

**Comment by JanX2** [comment] 2017-02-24 12:54
Interesting! 

It may appear to be more clean to bind `enabled` and `title`. I have tried that. The issue is that I could not find a simple way to have the menu item update it’s title when appropriate.

**Comment by JanX2** [comment] 2017-02-24 13:27
I got it working with just bindings. At least in the app I am currently working on, this requires implementing a lot of `+ (NSSet *)keyPathsForValuesAffecting…` methods.

**Comment by JanX2** [comment] 2017-02-24 14:15
Once I have release the code for the app ([Transcriptions](https://github.com/JanX2/Transcriptions)) it can be used as a reference for how to resolve this issue. If someone needs help before that, please get back to me here.

**Comment by Kentzo** [comment] 2017-02-24 19:39
@JanX2 Would worth to file a bug report to Apple as well.

**Comment by JanX2** [comment] 2017-02-24 21:55
@Kentzo 
It now appears to me to be more of a documentation issue. It makes some sense to disable `-validateMenuItem:` when bindings are used. It makes things more consistent in a way. But it ought to be documented with `-validateMenuItem:` and maybe a couple of other places.

**Comment by Kentzo** [comment] 2017-02-24 23:33
Would make sense to ask to update it then :)

Closing the issue as it's not a problem with ShortcutRecorder, but rather by design.

**Closed** 2017-02-24 23:35 UTC
Labels: bug, ShortcutRecorder
